# Generated by Django 5.0.1 on 2024-05-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_page_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='page_title',
            new_name='post_title',
        ),
    ]
