# Generated by Django 5.0.1 on 2024-02-12 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='address',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='race',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.person'),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.person')),
            ],
        ),
    ]
