# Generated by Django 5.0.1 on 2024-05-07 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('page_number', models.CharField(max_length=10)),
                ('page_publish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LikePAge',
            fields=[
                ('page_refrence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.page')),
                ('like', models.IntegerField()),
            ],
            bases=('account.page',),
        ),
    ]
